import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/layout/Navbar";
import { Poppins, Comforter_Brush, Unlock } from "next/font/google";
import Footer from "../components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add weights as needed
  variable: "--font-poppins", // Define a CSS variable
});

const comforterBrush = Comforter_Brush({
  subsets: ["latin"],
  weight: "400", // Comforter Brush supports only one weight
  variable: "--font-comforter", // Define a CSS variable for Comforter Brush
});
const unlock = Unlock({
  subsets: ["latin"],
  weight: "400", // Use the correct weight for the font
  variable: "--font-unlock", // Define a CSS variable
});
export const metadata: Metadata = {
  title: "North Craft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${comforterBrush.variable} ${unlock.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
