import { Image, Step } from "../utils/types";

export const steps: Step[] = [
  { title: "Evaluation And Signing Of The Contract" },
  { title: "Preparation Of The Work Plan" },
  { title: "Implementation Of Quality Works" },
  { title: "Delivering The Project To The Customer" },
];

export const images: Image[] = [
  {
    id: 1,
    url: "/assets/featured-project-images/img1.jpg",
    title: "Residential",
    category: "Building",
  },
  {
    id: 2,
    url: "/assets/featured-project-images/img2.jpg",
    title: "Apartments",
    category: "Renovations",
  },
  {
    id: 3,
    url: "/assets/featured-project-images/img3.jpg",
    title: "Townhomes",
    category: "Interior",
  },
  {
    id: 4,
    url: "/assets/featured-project-images/img4.jpg",
    title: "Multi Family House",
    category: "Luxury",
  },
  {
    id: 5,
    url: "/assets/featured-project-images/img5.png",
    title: "Luxury Villas",
    category: "Architecture",
  },
  {
    id: 6,
    url: "/assets/featured-project-images/img6.png",
    title: "Cottages",
    category: "Luxury",
  },
  {
    id: 7,
    url: "/assets/featured-project-images/img7.png",
    title: "Urban Flats",
    category: "Renovations",
  },
  {
    id: 8,
    url: "/assets/featured-project-images/img8.png",
    title: "Modern Condos",
    category: "Construction",
  },
  {
    id: 9,
    url: "/assets/featured-project-images/img9.png",
    title: "Eco Homes",
    category: "Architecture",
  },
  {
    id: 10,
    url: "/assets/featured-project-images/img10.png",
    title: "Family Residences",
    category: "Building",
  },
  {
    id: 10,
    url: "/assets/featured-project-images/img10.png",
    title: "Family Residences",
    category: "Building",
  },
  {
    id: 11,
    url: "/assets/featured-project-images/img1.jpg",
    title: "Residential",
    category: "Building",
  },
  {
    id: 12,
    url: "/assets/featured-project-images/img2.jpg",
    title: "Apartments",
    category: "Renovations",
  },
  {
    id: 13,
    url: "/assets/featured-project-images/img3.jpg",
    title: "Townhomes",
    category: "Interior",
  },
  {
    id: 14,
    url: "/assets/featured-project-images/img4.jpg",
    title: "Multi Family House",
    category: "Luxury",
  },
  {
    id: 15,
    url: "/assets/featured-project-images/img5.png",
    title: "Luxury Villas",
    category: "Architecture",
  },
  {
    id: 16,
    url: "/assets/featured-project-images/img6.png",
    title: "Cottages",
    category: "Luxury",
  },
  {
    id: 17,
    url: "/assets/featured-project-images/img7.png",
    title: "Urban Flats",
    category: "Renovations",
  },
  {
    id: 18,
    url: "/assets/featured-project-images/img8.png",
    title: "Modern Condos",
    category: "Construction",
  },
  {
    id: 19,
    url: "/assets/featured-project-images/img9.png",
    title: "Eco Homes",
    category: "Architecture",
  },
  {
    id: 20,
    url: "/assets/featured-project-images/img10.png",
    title: "Family Residences",
    category: "Building",
  },
  {
    id: 21,
    url: "/assets/featured-project-images/img1.jpg",
    title: "Residential",
    category: "Building",
  },
  {
    id: 22,
    url: "/assets/featured-project-images/img2.jpg",
    title: "Apartments",
    category: "Renovations",
  },
  {
    id: 23,
    url: "/assets/featured-project-images/img3.jpg",
    title: "Townhomes",
    category: "Interior",
  },
  {
    id: 24,
    url: "/assets/featured-project-images/img4.jpg",
    title: "Multi Family House",
    category: "Luxury",
  },
  {
    id: 25,
    url: "/assets/featured-project-images/img5.png",
    title: "Luxury Villas",
    category: "Architecture",
  },
  {
    id: 26,
    url: "/assets/featured-project-images/img6.png",
    title: "Cottages",
    category: "Luxury",
  },
  {
    id: 27,
    url: "/assets/featured-project-images/img7.png",
    title: "Urban Flats",
    category: "Renovations",
  },
  {
    id: 28,
    url: "/assets/featured-project-images/img8.png",
    title: "Modern Condos",
    category: "Construction",
  },
  {
    id: 29,
    url: "/assets/featured-project-images/img9.png",
    title: "Eco Homes",
    category: "Architecture",
  },
  {
    id: 30,
    url: "/assets/featured-project-images/img10.png",
    title: "Family Residences",
    category: "Building",
  },
];
